FROM python:3.11
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
LABEL maintainer="DUBAIL Séraphin seraphin.dubail@supinfo.com" #"MAINTAINER" est considéré comme obsolète depuis Docker 1.13