version: '3'
services:
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - voting-app:/data
    networks:
      - voting-app-network

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    container_name: result
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
    networks:
      - voting-app-network
    depends_on:
      - postgres
      - redis
    volumes:
      - voting-app:/app/data

  vote:
    build:
      context: ./vote
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
    networks:
      - voting-app-network
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./worker
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
    networks:
      - voting-app-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - voting-app:/app/data
    networks:
      - voting-app-network

networks:
  voting-app-network:

volumes:
  voting-app: